linters:
  PropertySortOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  SelectorFormat:
    enabled: false
  QualifyingElement:
    enabled: false
  StringQuotes:
    enabled: false
  PseudoElement:
    enabled: false
